import path from 'node:path';
import fs from 'fs-extra';
import glob from 'fast-glob';
import { AppConfig } from '../deploy/types.js';

export interface Logger {
  info: (msg: string) => void;
  warn: (msg: string) => void;
  error: (msg: string) => void;
}

export class EnvManager {
  constructor(private logger: Logger) {}

  /**
   * Discovers .env.example files and ensures all variables are represented in the root .env.
   * If root .env is missing, it creates it.
   * If it exists, it appends missing variables with their default values.
   */
  async ensureEnv(projectRoot: string) {
    const rootEnvPath = path.join(projectRoot, '.env');
    const exampleFiles = await glob(['**/.env.example', '.env.example'], {
      cwd: projectRoot,
      ignore: ['**/node_modules/**', '**/dist/**'],
    });

    if (exampleFiles.length === 0) {
      this.logger.warn('⚠️ No .env.example files found. Skipping .env processing.');
      return;
    }

    const exists = await fs.pathExists(rootEnvPath);
    let currentEnv: Record<string, string> = {};

    if (exists) {
      const content = await fs.readFile(rootEnvPath, 'utf8');
      currentEnv = this.parseEnv(content);
      this.logger.info('ℹ️ Root .env file exists. Checking for missing variables...');
    } else {
      this.logger.info('🔍 Root .env file missing. Generating from .env.example files...');
    }

    let mergedContent = exists
      ? await fs.readFile(rootEnvPath, 'utf8')
      : '# GENERATED BY NEXICAL\n# Merged from .env.example files\n\n';

    let addedCount = 0;
    const addedVars = new Set<string>();

    for (const file of exampleFiles.sort()) {
      const fullPath = path.join(projectRoot, file);
      const exampleContent = await fs.readFile(fullPath, 'utf8');
      const exampleEnv = this.parseEnv(exampleContent);

      let fileSectionAdded = false;

      for (const [key, value] of Object.entries(exampleEnv)) {
        if (!(key in currentEnv) && !addedVars.has(key)) {
          if (!fileSectionAdded && !exists) {
            mergedContent += `\n# --- Source: ${file} ---\n`;
            fileSectionAdded = true;
          } else if (!fileSectionAdded && exists) {
            mergedContent += `\n# --- Missing variables from ${file} ---\n`;
            fileSectionAdded = true;
          }

          mergedContent += `${key}=${value}\n`;
          addedVars.add(key);
          addedCount++;
        }
      }
    }

    if (addedCount > 0 || !exists) {
      await fs.writeFile(rootEnvPath, mergedContent.trim() + '\n');
      if (exists) {
        this.logger.info(`✅ Synchronized ${addedCount} missing variables to root .env.`);
      } else {
        this.logger.info(`✅ Generated root .env from ${exampleFiles.length} files.`);
      }
    } else {
      this.logger.info('✅ Root .env is up to date.');
    }
  }

  /**
   * Ensures that each application has a .env symlink pointing to the project root .env.
   */
  async ensureSymlinks(projectRoot: string, apps: AppConfig[]) {
    const rootEnvPath = path.join(projectRoot, '.env');

    if (!(await fs.pathExists(rootEnvPath))) {
      this.logger.warn('⚠️ Root .env missing, cannot create symlinks.');
      return;
    }

    for (const app of apps) {
      const appPath = app.target ? path.resolve(projectRoot, app.target) : projectRoot;

      // Skip if app is in root
      if (appPath === projectRoot) continue;

      const appEnvPath = path.join(appPath, '.env');

      try {
        const exists = await fs.pathExists(appEnvPath);

        if (exists) {
          const lstat = await fs.lstat(appEnvPath);
          if (lstat.isSymbolicLink()) {
            const target = await fs.readlink(appEnvPath);
            const absoluteTarget = path.resolve(appPath, target);
            if (absoluteTarget === rootEnvPath) continue;
          }
          await fs.remove(appEnvPath);
        }

        const relativeRootEnv = path.relative(appPath, rootEnvPath);
        await fs.symlink(relativeRootEnv, appEnvPath);
        this.logger.info(`🔗 Created/Updated .env symlink for ${app.name}`);
      } catch (e: unknown) {
        this.logger.warn(
          `⚠️ Failed to create symlink for ${app.name}: ${e instanceof Error ? e.message : String(e)}`,
        );
      }
    }
  }

  /**
   * Simple parser for .env files.
   */
  private parseEnv(content: string): Record<string, string> {
    const lines = content.split('\n');
    const result: Record<string, string> = {};

    for (const line of lines) {
      const trimmedLine = line.trim();
      if (!trimmedLine || trimmedLine.startsWith('#')) continue;

      const match = trimmedLine.match(/^([^=]+)=(.*)$/);
      if (match) {
        const key = match[1].trim();
        let value = match[2].trim();

        // Remove quotes if present
        if (
          (value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))
        ) {
          value = value.substring(1, value.length - 1);
        }

        result[key] = value;
      }
    }

    return result;
  }
}
